### ISSUE TITLE
TC loss is negative

### ISSUE THREAD

**Issue by Shunsuke-1994** [welch-lab/MichiGAN#1]
Hi! Thank you for sharing your codes!

When I look at your beta-TCVAE implementation, I found your TC loss is negative in `FunctionProgramExamples/examples/example_beta_TCVAE.ipynb`.

```
epoch: 98; iteration: 3168; beta-TCVAE loss:4330.94580078125; Total Correlation:-0.8152694702148438
epoch: 99; iteration: 3200; beta-TCVAE loss:4333.12744140625; Total Correlation:-1.0267829895019531
```

However, in principle, TC loss should be positive.
Why is your TC loss negative?

Best,

**Comment by hengshiyu** [comment]
Hi, thank you for the good question. The total correlation (TC) is KL[q(Z) || q(Z1)...q(Zn)] = E_{q(Z)}[logq(Z)] - \sum E_{q(Z)}[logq(Zi)], where both terms have no closed forms from VAEs and can only be stochastically approximated. The stochastically approximating estimators are also lower bounds of the two terms themselves. Thus, the estimated KL divergence is a biased estimate. 

Therefore, when the true KL divergence is small and close to 0, the approximating KL estimate is possible to be negative, especially in a minibatch with limited samples for the approximating estimators. The negative values of the TC estimator indicate a true TC with value close to 0.
